//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exhibition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int SN { get; set; }
        public string Path { get; set; }
        public string Message { get; set; }
        public string Stack { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> ErrorDate { get; set; }
    }
}
