//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exhibition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int SN { get; set; }
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> ReservationBegin { get; set; }
        public Nullable<System.DateTime> ReservationEnd { get; set; }
        public string ContactName { get; set; }
        public string ContactMobile { get; set; }
        public string ContactEmail { get; set; }
        public string ContactNote { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CreateSource { get; set; }
        public string ModifySource { get; set; }
        public Nullable<int> TouristType { get; set; }
        public Nullable<int> TouristRange1 { get; set; }
        public Nullable<int> TouristRange2 { get; set; }
        public string GroupName { get; set; }
        public string VerifyCode { get; set; }
        public Nullable<System.DateTime> VerifyDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> GroupType { get; set; }
        public Nullable<int> TouristNo { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelSource { get; set; }
        public string CancelUserId { get; set; }
        public Nullable<int> StateCode { get; set; }
        public string CreateUserId { get; set; }
        public string ModifyUserId { get; set; }
        public string VerifyUserId { get; set; }
        public string DeleteUserId { get; set; }
        public string DeleteSource { get; set; }
        public string VerifySource { get; set; }
        public Nullable<int> NationForeigner { get; set; }
        public Nullable<int> NationNative { get; set; }
        public Nullable<int> MemberGov { get; set; }
        public Nullable<int> MemberNGO { get; set; }
        public Nullable<int> MemberEdu { get; set; }
        public Nullable<int> MemberOther { get; set; }
        public string TourNo { get; set; }
        public string TourLeader { get; set; }
        public string TourGuide { get; set; }
        public string TourField { get; set; }
        public Nullable<System.DateTime> AuthDate { get; set; }
        public string AuthUserId { get; set; }
        public string AuthSource { get; set; }
    }
}
